<a href="https://colab.research.google.com/github/Rayr07/ML-lab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = [1, 2, 3, 4, 5]
print("Original List:",a)
np_arr = np.array(a)
print("NumPy Array:",a)
print("Shape of the array:", np_arr.shape)
print("Data type of the array:", np_arr.dtype)

Original List: [1, 2, 3, 4, 5]
NumPy Array: [1, 2, 3, 4, 5]
Shape of the array: (5,)
Data type of the array: int64


In [ ]:
import numpy as np
z = np.zeros((3, 4))
print(f"Zeros Matrix:\n{z}")
print(f"Shape of Matrix: {z.shape}\n")

o = np.ones((2, 5))
print(f"Ones Matrix:\n{o}")
print(f"Shape of Matrix: {o}")

Zeros Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape of Matrix: (3, 4)

Ones Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape of Matrix: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
a = np.arange(1, 13)
print("Original Array:",a)
print("Shape of Array:",a)
r = a.reshape(3, 4)
print(f"Reshaped Array:\n {r}")
print(f"Shape of Reshaped Array:\n {r}")

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape of Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np

a = np.random.randint(1, 101, 10)
print("Random Integers Array:",a)

print(f"Minimum value:", a.min())
print(f"Maximum value:",a.max())
print(f"Mean value:", a.mean())
print(f"Sum of values:", a.sum())

Random Integers Array: [68 80 97 12 79 25 67  8 74 63]
Minimum value: 8
Maximum value: 97
Mean value: 57.3
Sum of values: 573


In [ ]:
import pandas as pd
data = {
    'Name': ['Sarah', 'Babita', 'Charles', 'Hiya'],
    'Marks': [85, 92, 78, 95]
}
df = pd.DataFrame(data)
print("Students DataFrame:\n", df)
print("\nData Types of DataFrame columns:\n", df.dtypes)

Students DataFrame:
       Name  Marks
0    Sarah     85
1   Babita     92
2  Charles     78
3     Hiya     95

Data Types of DataFrame columns:
 Name     object
Marks     int64
dtype: object


In [20]:
iris_df = pd.read_csv('/content/Iris.csv')
print("First 5 rows of the DataFrame:")
print(iris_df.head())
print("Last 5 rows of the DataFrame:")
print(iris_df.tail())

First 5 rows of the DataFrame:
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
Last 5 rows of the DataFrame:
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-vi

In [24]:
iris_df.info()
print("\nNumber of rows:",len(iris_df))
print("\nNumber of columns:", df.shape[1])
print("\nMissing values per column:")
print(iris_df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

Number of rows: 150

Number of columns: 2

Missing values per column:
Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64


In [21]:
print("Statistical summary of numerical columns:")
print(iris_df.describe())

Statistical summary of numerical columns:
               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000
